
CREATE TABLE CONTINENT(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255)
);
ALTER TABLE CONTINENT ADD CONSTRAINT PK_CT PRIMARY KEY(ID);


CREATE TABLE COUNTRY(
    ID BIGINT NOT NULL,
    FLAG VARCHAR(255),
    NAME VARCHAR(255),
    CONTINENT_ID BIGINT
);
ALTER TABLE COUNTRY ADD CONSTRAINT PK_CY PRIMARY KEY(ID);
ALTER TABLE COUNTRY ADD CONSTRAINT FKCY_CP FOREIGN KEY(CONTINENT_ID) REFERENCES CONTINENT(ID);



CREATE TABLE CONTINENT_AUD(
    ID BIGINT NOT NULL,
    REV INTEGER NOT NULL,
    REVTYPE TINYINT,
    NAME VARCHAR(255)
);
ALTER TABLE CONTINENT_AUD ADD CONSTRAINT PK_CTA PRIMARY KEY(ID, REV);
ALTER TABLE CONTINENT_AUD ADD CONSTRAINT FK_CTA_REV FOREIGN KEY(REV) REFERENCES REVINFO(REV);

CREATE TABLE COUNTRY_AUD(
    ID BIGINT NOT NULL,
    REV INTEGER NOT NULL,
    REVTYPE TINYINT,
    FLAG VARCHAR(255),
    NAME VARCHAR(255),
    CONTINENT_ID BIGINT
);
ALTER TABLE COUNTRY_AUD ADD CONSTRAINT PK_CYA PRIMARY KEY(ID, REV);
ALTER TABLE COUNTRY_AUD ADD CONSTRAINT FK_CYA_REV FOREIGN KEY(REV) REFERENCES REVINFO(REV);


CREATE TABLE REVINFO(
    REV INTEGER DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_2F871928_1EE4_4B60_A962_07ED5CD16818) NOT NULL NULL_TO_DEFAULT SEQUENCE SYSTEM_SEQUENCE_2F871928_1EE4_4B60_A962_07ED5CD16818,
    REVTSTMP BIGINT
);
ALTER TABLE REVINFO ADD CONSTRAINT PK_REV PRIMARY KEY(REV);